version: '3.8'

services:
  web:
    working_dir: /app
    build: 
      context: ./frontend
    ports:
    # Host:Container
      - 5173:5173
    depends_on:
      - db
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - "/app/node_modules"
    ports:
      - 5050:5050
    environment:
      DB_URL: mongodb://db:27017/airneisDB
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    depends_on:
      - db


volumes:
  database: